# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/pc/Desktop/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/pc/Desktop/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/pc/Desktop/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/pc/Desktop/project_1/project_1.srcs/sources_1/new/ALU_ctrlunit.v
  C:/Users/pc/Desktop/project_1/project_1.srcs/sources_1/new/COMPinstruction_mux.v
  C:/Users/pc/Desktop/project_1/project_1.srcs/sources_1/new/ForwardUnit.v
  C:/Users/pc/Desktop/project_1/project_1.srcs/sources_1/new/ImmGen.v
  C:/Users/pc/Desktop/project_1/project_1.srcs/sources_1/new/JALR_PC2mux.v
  C:/Users/pc/Desktop/project_1/project_1.srcs/sources_1/new/MUXflush.v
  C:/Users/pc/Desktop/project_1/project_1.srcs/sources_1/imports/imports/new/Mul_unit.v
  C:/Users/pc/Desktop/project_1/project_1.srcs/sources_1/new/RD_mux.v
  C:/Users/pc/Desktop/project_1/project_1.srcs/sources_1/imports/imports/new/RVC.v
  C:/Users/pc/Desktop/project_1/project_1.srcs/sources_1/new/alu.v
  C:/Users/pc/Desktop/project_1/project_1.srcs/sources_1/new/andgate.v
  C:/Users/pc/Desktop/project_1/project_1.srcs/sources_1/imports/imports/Desktop/branch_mux.v
  C:/Users/pc/Desktop/project_1/project_1.srcs/sources_1/new/ctrlunit.v
  C:/Users/pc/Desktop/project_1/project_1.srcs/sources_1/new/dflipflop.v
  C:/Users/pc/Desktop/project_1/project_1.srcs/sources_1/new/fulladd.v
  C:/Users/pc/Desktop/project_1/project_1.srcs/sources_1/new/memory.v
  C:/Users/pc/Desktop/project_1/project_1.srcs/sources_1/new/mux.v
  C:/Users/pc/Desktop/project_1/project_1.srcs/sources_1/new/mux3to1.v
  C:/Users/pc/Desktop/project_1/project_1.srcs/sources_1/new/muxx.v
  C:/Users/pc/Desktop/project_1/project_1.srcs/sources_1/new/nbit.v
  C:/Users/pc/Desktop/project_1/project_1.srcs/sources_1/new/prv32_ALU.v
  C:/Users/pc/Desktop/project_1/project_1.srcs/sources_1/new/regs.v
  C:/Users/pc/Desktop/project_1/project_1.srcs/sources_1/new/shift.v
  C:/Users/pc/Desktop/project_1/project_1.srcs/sources_1/new/shifter.v
  C:/Users/pc/Desktop/project_1/project_1.srcs/sources_1/new/DataPath.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/pc/Desktop/project_1/project_1.srcs/constrs_1/new/consss.xdc
set_property used_in_implementation false [get_files C:/Users/pc/Desktop/project_1/project_1.srcs/constrs_1/new/consss.xdc]


synth_design -top DataPath -part xc7a100tcsg324-1


write_checkpoint -force -noxdef DataPath.dcp

catch { report_utilization -file DataPath_utilization_synth.rpt -pb DataPath_utilization_synth.pb }
